### ISSUE TITLE
Categorization & Search plugins don't works

### ISSUE THREAD

**Issue by elkwaet** [BesrourMS/magazine#6]
Hi @BesrourMS,
I begin use Pico with the theme Magazine to manage my personnal blog.
I have several issue with internal search and categories filter.
i followed correctly instructions and can set catagories in the header section of any page/articles. But, it is not possible to filter content for a specific catgory in the collaopse Menu. All my tentatives in goal to set it manualy with Html balises in the index.twig file dont succed:
__http://url/catagories/category1__
__http://url/catagories/category2__
__http://url/catagory1__
For the search plugin, it is not works simply.
I need help to set it please;
Thanks in advance

**Comment by BesrourMS** [comment]
https://github.com/BesrourMS/magazine/pull/4
